//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CoreSQL.Entities", "FK_zonas_altura_zonas_calle", "zonas_calle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CoreSQL.Entities.Calle), "zonas_altura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CoreSQL.Entities.Altura), true)]
[assembly: EdmRelationshipAttribute("CoreSQL.Entities", "FK_zonas_calle_zonas_localidad", "zonas_localidad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CoreSQL.Entities.Localidad), "zonas_calle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CoreSQL.Entities.Calle), true)]

#endregion

namespace CoreSQL.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AikeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AikeEntities object using the connection string found in the 'AikeEntities' section of the application configuration file.
        /// </summary>
        public AikeEntities() : base("name=AikeEntities", "AikeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AikeEntities object.
        /// </summary>
        public AikeEntities(string connectionString) : base(connectionString, "AikeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AikeEntities object.
        /// </summary>
        public AikeEntities(EntityConnection connection) : base(connection, "AikeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Altura> zonas_altura
        {
            get
            {
                if ((_zonas_altura == null))
                {
                    _zonas_altura = base.CreateObjectSet<Altura>("zonas_altura");
                }
                return _zonas_altura;
            }
        }
        private ObjectSet<Altura> _zonas_altura;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Calle> zonas_calle
        {
            get
            {
                if ((_zonas_calle == null))
                {
                    _zonas_calle = base.CreateObjectSet<Calle>("zonas_calle");
                }
                return _zonas_calle;
            }
        }
        private ObjectSet<Calle> _zonas_calle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Localidad> zonas_localidad
        {
            get
            {
                if ((_zonas_localidad == null))
                {
                    _zonas_localidad = base.CreateObjectSet<Localidad>("zonas_localidad");
                }
                return _zonas_localidad;
            }
        }
        private ObjectSet<Localidad> _zonas_localidad;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the zonas_altura EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTozonas_altura(Altura altura)
        {
            base.AddObject("zonas_altura", altura);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the zonas_calle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTozonas_calle(Calle calle)
        {
            base.AddObject("zonas_calle", calle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the zonas_localidad EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTozonas_localidad(Localidad localidad)
        {
            base.AddObject("zonas_localidad", localidad);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="alturaDesdeNumero">No Metadata Documentation available.</param>
        /// <param name="alturaHastaNumero">No Metadata Documentation available.</param>
        /// <param name="calleNombre">No Metadata Documentation available.</param>
        public ObjectResult<AlturasCalle> GetAlturasByProximidad(Nullable<global::System.Int32> alturaDesdeNumero, Nullable<global::System.Int32> alturaHastaNumero, global::System.String calleNombre)
        {
            ObjectParameter alturaDesdeNumeroParameter;
            if (alturaDesdeNumero.HasValue)
            {
                alturaDesdeNumeroParameter = new ObjectParameter("AlturaDesdeNumero", alturaDesdeNumero);
            }
            else
            {
                alturaDesdeNumeroParameter = new ObjectParameter("AlturaDesdeNumero", typeof(global::System.Int32));
            }
    
            ObjectParameter alturaHastaNumeroParameter;
            if (alturaHastaNumero.HasValue)
            {
                alturaHastaNumeroParameter = new ObjectParameter("AlturaHastaNumero", alturaHastaNumero);
            }
            else
            {
                alturaHastaNumeroParameter = new ObjectParameter("AlturaHastaNumero", typeof(global::System.Int32));
            }
    
            ObjectParameter calleNombreParameter;
            if (calleNombre != null)
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", calleNombre);
            }
            else
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<AlturasCalle>("GetAlturasByProximidad", alturaDesdeNumeroParameter, alturaHastaNumeroParameter, calleNombreParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="alturaNumero">No Metadata Documentation available.</param>
        /// <param name="calleNombre">No Metadata Documentation available.</param>
        public ObjectResult<AlturasCalle> GetAlturasByRango(Nullable<global::System.Int32> alturaNumero, global::System.String calleNombre)
        {
            ObjectParameter alturaNumeroParameter;
            if (alturaNumero.HasValue)
            {
                alturaNumeroParameter = new ObjectParameter("AlturaNumero", alturaNumero);
            }
            else
            {
                alturaNumeroParameter = new ObjectParameter("AlturaNumero", typeof(global::System.Int32));
            }
    
            ObjectParameter calleNombreParameter;
            if (calleNombre != null)
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", calleNombre);
            }
            else
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<AlturasCalle>("GetAlturasByRango", alturaNumeroParameter, calleNombreParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="calleNombre">No Metadata Documentation available.</param>
        public ObjectResult<Calle> GetCallesByNombre(global::System.String calleNombre)
        {
            ObjectParameter calleNombreParameter;
            if (calleNombre != null)
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", calleNombre);
            }
            else
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Calle>("GetCallesByNombre", calleNombreParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="calleNombre">No Metadata Documentation available.</param>
        public ObjectResult<Calle> GetCallesByNombre(global::System.String calleNombre, MergeOption mergeOption)
        {
            ObjectParameter calleNombreParameter;
            if (calleNombre != null)
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", calleNombre);
            }
            else
            {
                calleNombreParameter = new ObjectParameter("CalleNombre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Calle>("GetCallesByNombre", mergeOption, calleNombreParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoreSQL.Entities", Name="Altura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Altura : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Altura object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="calle_id">Initial value of the calle_id property.</param>
        /// <param name="desde">Initial value of the desde property.</param>
        /// <param name="hasta">Initial value of the hasta property.</param>
        /// <param name="vereda">Initial value of the vereda property.</param>
        /// <param name="barrio">Initial value of the barrio property.</param>
        public static Altura CreateAltura(global::System.Int32 id, global::System.Int32 calle_id, global::System.Int32 desde, global::System.Int32 hasta, global::System.Int16 vereda, global::System.String barrio)
        {
            Altura altura = new Altura();
            altura.id = id;
            altura.calle_id = calle_id;
            altura.desde = desde;
            altura.hasta = hasta;
            altura.vereda = vereda;
            altura.barrio = barrio;
            return altura;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 calle_id
        {
            get
            {
                return _calle_id;
            }
            set
            {
                Oncalle_idChanging(value);
                ReportPropertyChanging("calle_id");
                _calle_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("calle_id");
                Oncalle_idChanged();
            }
        }
        private global::System.Int32 _calle_id;
        partial void Oncalle_idChanging(global::System.Int32 value);
        partial void Oncalle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 desde
        {
            get
            {
                return _desde;
            }
            set
            {
                OndesdeChanging(value);
                ReportPropertyChanging("desde");
                _desde = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desde");
                OndesdeChanged();
            }
        }
        private global::System.Int32 _desde;
        partial void OndesdeChanging(global::System.Int32 value);
        partial void OndesdeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hasta
        {
            get
            {
                return _hasta;
            }
            set
            {
                OnhastaChanging(value);
                ReportPropertyChanging("hasta");
                _hasta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasta");
                OnhastaChanged();
            }
        }
        private global::System.Int32 _hasta;
        partial void OnhastaChanging(global::System.Int32 value);
        partial void OnhastaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 vereda
        {
            get
            {
                return _vereda;
            }
            set
            {
                OnveredaChanging(value);
                ReportPropertyChanging("vereda");
                _vereda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vereda");
                OnveredaChanged();
            }
        }
        private global::System.Int16 _vereda;
        partial void OnveredaChanging(global::System.Int16 value);
        partial void OnveredaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> zona
        {
            get
            {
                return _zona;
            }
            set
            {
                OnzonaChanging(value);
                ReportPropertyChanging("zona");
                _zona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zona");
                OnzonaChanged();
            }
        }
        private Nullable<global::System.Int16> _zona;
        partial void OnzonaChanging(Nullable<global::System.Int16> value);
        partial void OnzonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String barrio
        {
            get
            {
                return _barrio;
            }
            set
            {
                OnbarrioChanging(value);
                ReportPropertyChanging("barrio");
                _barrio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("barrio");
                OnbarrioChanged();
            }
        }
        private global::System.String _barrio;
        partial void OnbarrioChanging(global::System.String value);
        partial void OnbarrioChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoreSQL.Entities", Name="Calle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Calle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Calle object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="nombres">Initial value of the nombres property.</param>
        /// <param name="localidad_id">Initial value of the localidad_id property.</param>
        public static Calle CreateCalle(global::System.Int32 id, global::System.String nombre, global::System.String nombres, global::System.Int32 localidad_id)
        {
            Calle calle = new Calle();
            calle.id = id;
            calle.nombre = nombre;
            calle.nombres = nombres;
            calle.localidad_id = localidad_id;
            return calle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombres
        {
            get
            {
                return _nombres;
            }
            set
            {
                OnnombresChanging(value);
                ReportPropertyChanging("nombres");
                _nombres = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombres");
                OnnombresChanged();
            }
        }
        private global::System.String _nombres;
        partial void OnnombresChanging(global::System.String value);
        partial void OnnombresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 localidad_id
        {
            get
            {
                return _localidad_id;
            }
            set
            {
                Onlocalidad_idChanging(value);
                ReportPropertyChanging("localidad_id");
                _localidad_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("localidad_id");
                Onlocalidad_idChanged();
            }
        }
        private global::System.Int32 _localidad_id;
        partial void Onlocalidad_idChanging(global::System.Int32 value);
        partial void Onlocalidad_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreSQL.Entities", "FK_zonas_altura_zonas_calle", "zonas_altura")]
        public EntityCollection<Altura> altura_set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Altura>("CoreSQL.Entities.FK_zonas_altura_zonas_calle", "zonas_altura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Altura>("CoreSQL.Entities.FK_zonas_altura_zonas_calle", "zonas_altura", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreSQL.Entities", "FK_zonas_calle_zonas_localidad", "zonas_localidad")]
        public Localidad localidad_set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localidad>("CoreSQL.Entities.FK_zonas_calle_zonas_localidad", "zonas_localidad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localidad>("CoreSQL.Entities.FK_zonas_calle_zonas_localidad", "zonas_localidad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Localidad> localidad_setReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localidad>("CoreSQL.Entities.FK_zonas_calle_zonas_localidad", "zonas_localidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Localidad>("CoreSQL.Entities.FK_zonas_calle_zonas_localidad", "zonas_localidad", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoreSQL.Entities", Name="Localidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Localidad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Localidad object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static Localidad CreateLocalidad(global::System.Int32 id, global::System.String nombre)
        {
            Localidad localidad = new Localidad();
            localidad.id = id;
            localidad.nombre = nombre;
            return localidad;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreSQL.Entities", "FK_zonas_calle_zonas_localidad", "zonas_calle")]
        public EntityCollection<Calle> calle_set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Calle>("CoreSQL.Entities.FK_zonas_calle_zonas_localidad", "zonas_calle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Calle>("CoreSQL.Entities.FK_zonas_calle_zonas_localidad", "zonas_calle", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CoreSQL.Entities", Name="AlturasCalle")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AlturasCalle : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AlturasCalle object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="calle_id">Initial value of the calle_id property.</param>
        /// <param name="calle_nombre">Initial value of the calle_nombre property.</param>
        /// <param name="desde">Initial value of the desde property.</param>
        /// <param name="hasta">Initial value of the hasta property.</param>
        /// <param name="vereda">Initial value of the vereda property.</param>
        /// <param name="barrio">Initial value of the barrio property.</param>
        public static AlturasCalle CreateAlturasCalle(global::System.Int32 id, global::System.Int32 calle_id, global::System.String calle_nombre, global::System.Int32 desde, global::System.Int32 hasta, global::System.Int16 vereda, global::System.String barrio)
        {
            AlturasCalle alturasCalle = new AlturasCalle();
            alturasCalle.id = id;
            alturasCalle.calle_id = calle_id;
            alturasCalle.calle_nombre = calle_nombre;
            alturasCalle.desde = desde;
            alturasCalle.hasta = hasta;
            alturasCalle.vereda = vereda;
            alturasCalle.barrio = barrio;
            return alturasCalle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 calle_id
        {
            get
            {
                return _calle_id;
            }
            set
            {
                Oncalle_idChanging(value);
                ReportPropertyChanging("calle_id");
                _calle_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("calle_id");
                Oncalle_idChanged();
            }
        }
        private global::System.Int32 _calle_id;
        partial void Oncalle_idChanging(global::System.Int32 value);
        partial void Oncalle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String calle_nombre
        {
            get
            {
                return _calle_nombre;
            }
            set
            {
                Oncalle_nombreChanging(value);
                ReportPropertyChanging("calle_nombre");
                _calle_nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("calle_nombre");
                Oncalle_nombreChanged();
            }
        }
        private global::System.String _calle_nombre;
        partial void Oncalle_nombreChanging(global::System.String value);
        partial void Oncalle_nombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 desde
        {
            get
            {
                return _desde;
            }
            set
            {
                OndesdeChanging(value);
                ReportPropertyChanging("desde");
                _desde = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desde");
                OndesdeChanged();
            }
        }
        private global::System.Int32 _desde;
        partial void OndesdeChanging(global::System.Int32 value);
        partial void OndesdeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hasta
        {
            get
            {
                return _hasta;
            }
            set
            {
                OnhastaChanging(value);
                ReportPropertyChanging("hasta");
                _hasta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasta");
                OnhastaChanged();
            }
        }
        private global::System.Int32 _hasta;
        partial void OnhastaChanging(global::System.Int32 value);
        partial void OnhastaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 vereda
        {
            get
            {
                return _vereda;
            }
            set
            {
                OnveredaChanging(value);
                ReportPropertyChanging("vereda");
                _vereda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vereda");
                OnveredaChanged();
            }
        }
        private global::System.Int16 _vereda;
        partial void OnveredaChanging(global::System.Int16 value);
        partial void OnveredaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> zona
        {
            get
            {
                return _zona;
            }
            set
            {
                OnzonaChanging(value);
                ReportPropertyChanging("zona");
                _zona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zona");
                OnzonaChanged();
            }
        }
        private Nullable<global::System.Int16> _zona;
        partial void OnzonaChanging(Nullable<global::System.Int16> value);
        partial void OnzonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String barrio
        {
            get
            {
                return _barrio;
            }
            set
            {
                OnbarrioChanging(value);
                ReportPropertyChanging("barrio");
                _barrio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("barrio");
                OnbarrioChanged();
            }
        }
        private global::System.String _barrio;
        partial void OnbarrioChanging(global::System.String value);
        partial void OnbarrioChanged();

        #endregion
    }

    #endregion
    
}
